name: build

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  check-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

      name: npm install and next build
      run: |
        npm install
        npm run build
